package main

import (
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"sort"
	"strings"
)

// Generate biome colors from the same Java Edition jar as the base textures.
func (a *assets) writeBiomeColors(out string) error {
	maps := make(map[string]image.Image)
	for _, kind := range []string{"grass", "foliage"} {
		file := a.files["assets/minecraft/textures/colormap/"+kind+".png"]
		if file == nil {
			return fmt.Errorf("missing %s colormap", kind)
		}
		r, err := file.Open()
		if err != nil {
			return err
		}
		img, err := png.Decode(r)
		r.Close()
		if err != nil {
			return err
		}
		if img.Bounds().Dx() != 256 || img.Bounds().Dy() != 256 {
			return fmt.Errorf("invalid %s colormap dimensions", kind)
		}
		maps[kind] = img
	}
	var names []string
	for name := range a.files {
		if strings.HasPrefix(name, "data/minecraft/worldgen/biome/") && strings.HasSuffix(name, ".json") {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return fmt.Errorf("no biome definitions in jar")
	}
	sort.Strings(names)
	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by gen_colors from Minecraft biome definitions and colormaps; DO NOT EDIT.\npackage main\n\nvar biomeTints = map[string]biomeTint{")
	for _, name := range names {
		var def struct {
			Temperature float64 `json:"temperature"`
			Downfall    float64 `json:"downfall"`
			Effects     struct {
				Grass    *uint32 `json:"grass_color"`
				Foliage  *uint32 `json:"foliage_color"`
				Water    uint32  `json:"water_color"`
				Modifier string  `json:"grass_color_modifier"`
			} `json:"effects"`
		}
		if err := a.readJSON(name, &def); err != nil {
			return err
		}
		temp := max(0, min(1, def.Temperature))
		rain := max(0, min(1, def.Downfall)) * temp
		sample := func(kind string) uint32 {
			c := color.NRGBAModel.Convert(maps[kind].At(int((1-temp)*255), int((1-rain)*255))).(color.NRGBA)
			return uint32(c.R)<<16 | uint32(c.G)<<8 | uint32(c.B)
		}
		grass, foliage := sample("grass"), sample("foliage")
		if def.Effects.Grass != nil {
			grass = *def.Effects.Grass
		}
		if def.Effects.Foliage != nil {
			foliage = *def.Effects.Foliage
		}
		switch def.Effects.Modifier {
		case "dark_forest":
			grass = ((grass & 0xfefefe) + 0x28340a) >> 1
		// Use the common swamp shade for the map; vanilla varies between two
		// shades using positional noise, which this one-color-per-biome map omits.
		case "swamp":
			grass = 0x6a7039
		}
		id := "minecraft:" + strings.TrimSuffix(strings.TrimPrefix(name, "data/minecraft/worldgen/biome/"), ".json")
		fmt.Fprintf(&b, "%q: {Grass: 0x%06x, Foliage: 0x%06x, Water: 0x%06x},\n", id, grass, foliage, def.Effects.Water)
	}
	fmt.Fprintln(&b, "}")
	return os.WriteFile(out, []byte(b.String()), 0644)
}
